### ISSUE TITLE
Inconsistent country iso3 codes

### ISSUE THREAD

**Issue by marius-mather** [monarch-initiative/vertebrate-breed-ontology#110]
While attempting to match VBO entries to DAD-IS, I noticed that in the ncbibreeds spreadsheet (https://github.com/monarch-initiative/vertebrate-breed-ontology/blob/master/src/ontology/components/ncbibreeds.tsv), the listed country name in the Country column doesn't always correspond to the ISO3 code in the "exists_in_country" column. 

e.g. VBO:0016789: Dinde locale, Togo (Turkey) is listed with a Country of Togo and an ISO3 code of TCD (Chad). DAD-IS lists this breed in Togo.

Looking at the spreadsheet more closely it looks like the ISO3 codes were bumped down by one row somewhere, as the correct ISO3 codes appear one row down from their entries.

If the Country column is correct, it looks like the fix for this is to match the Country values to their correct ISO3 codes.

**Comment by sabrinatoro** [comment]
ISO3 codes for country have been updated in the main spreadsheet (the country column was assumed correct).
Changes will be visible in the ontology after we update the components. 

@marius-mather, I think this issue can be closed (unless something else is required).


FYI: @katiermullen @franknic @ImkeTammen

**Comment by marius-mather** [comment]
Thanks, I've checked the master spreadsheet and it looks like this is fixed, closing 👍
