### ISSUE TITLE
Persian sheep in Australia

### ISSUE THREAD

**Issue by ImkeTammen** [monarch-initiative/vertebrate-breed-ontology#114]
I am trying to add a VBO ID to a paper for Persian sheep in Australia.

There is an entry for this in DADIS  https://www.fao.org/dad-is/browse-by-country-and-species/en/ but I couldn't find one in VBO (and here is the link to the Australian breed society: https://www.australianpersiansheepassociation.com/)

It looks to me that the transboundary 'Blackheaded Persian' VBO_0001339 sheep is not a fit as transboundary for Persian sheep in Australia, as it is to narrow (the Australian ones are not all blackheaded) - and in DADIS Persian sheep in Australia don't have a transboundary link. There are a few other 'Persian' sheep country breeds listed under VBO_0001339 - not sure if they are all blackheaded or if a new 'Persian' transboundary VBO in addition to a Persian sheep (Australia) VBO.

Imke

For new term requests, please provide the following information:

## Preferred term label

(e.g., Asplenia)

## Synonyms

(e.g., Absent spleen)

## Textual definition

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/ubo)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by franknic** [comment]
Imke and I have discussed this today. The biological reality around the world is that Blackhead is just one variety of Persian sheep, e.g. https://southafrica.co.za/breeds-sheep-meat-south-africa.html. In the past it has been by far the most common type in most, if not all, countries, which explains why the transboundary name has been "Blackhead Persian". Now, however, it is the minority phenotype in countries like Australia (See, e.g. https://www.australianpersiansheepassociation.com/australian-persian-sheep-association-show-champions.html).
The best strategy is to do as Imke has suggested, namely to retain VBO:001339 as the transboundary id but to change its name from "Blackhead Persian" to "Persian".
So, the recommendations are:
1. Change the transboundary entry Blackhead Persian (Sheep)VBO:0001339 to Persian (Sheep)VBO:0001339
2. Create a new national breed Persian, Australia (Sheep) VBO:xxxxxxx, with transboundary Persian (Sheep)VBO:0001339
3. To tidy up another entry, allocate transboundary Persian (Sheep)VBO:0001339 to Red Head Persian, Mozambique (Sheep)VBO:0016266

**Comment by katiermullen** [comment]
@ImkeTammen @franknic Thank you for your input!

We are trying to avoid adding additional breed_country terms in VBO unless they originate from DAD-IS, where terms are clearly defined by breed, country and species. 

It appears that the Persian sheep in Australia were imported as embryos https://www.australianpersiansheepassociation.com/australian-persian-sheep-association-importation-into-australia.html so they may not be distinct from Persian sheep in other countries.

I can add a grouping term, "Persian (Sheep)" and children will be:
- Blackhead Persian (Sheep)VBO:0001339
- Red Head Persian, Mozambique (Sheep)VBO:0016266

You can then annotate your data with the new VBO ID for "Persian (Sheep)".

**Comment by katiermullen** [comment]
Discussed at VBO call on 2023-09-07:

- Note: DADIS definition of a national breed is only that the breed exists/occurs in that country.
- Also note that ok to add a new breed concept "Persian (Sheep)" as indicated above.  
- The new DADIS file has a term for Persian, Australia (Sheep). This should be apparent when we establish the synchronization pipeline with DADIS. If Imke needs this concept added sooner, we can reserve a VBO ID for it.
