### ISSUE TITLE
Add reference for Chilean Terrier

### ISSUE THREAD

**Issue by katiermullen** [monarch-initiative/vertebrate-breed-ontology#122]
Please add new reference for Chilean Terrier per request of @franknic: 

Chilean Terrier dogs (VBO_0200342). The pmid is [37778752](https://pubmed.ncbi.nlm.nih.gov/37778752/).

**Comment by katiermullen** [comment]
completed #124

**Comment by franknic** [comment]
Thank you very much, Katie!
