### ISSUE TITLE
Subset information (e.g. transboundary) not shown in OLS4

### ISSUE THREAD

**Issue by marius-mather** [monarch-initiative/vertebrate-breed-ontology#126]
In the OLS3 API it was possible to tell whether a breed was a transboundary term using the subset/in_subset property. In OLS4 this currently seems to be `null` for all VBO terms. I've opened an issue against OLS4 in case they can offer advice: https://github.com/EBISPOT/ols4/issues/581, but given that Mondo subsets are showing in OLS4, I think it may be about how VBO is configured.

I'm not sure exactly where to define the subset properties that VBO uses, I can see references to subsets in the `Makefile` but I'm not sure if that's the best place to define it, so any advice would be appreciated.

**Comment by sabrinatoro** [comment]
@marius-mather 
This is not an error in OLS, it is on us: 
We removed the "in_subset - transboundary" property in the latest release because it was a confusing piece of information (and only people who are deep in DADIS/FAO work understand what it is). 

Do you need this information? If we have a use case, we can add it easily.

**Comment by marius-mather** [comment]
Ah, that makes sense! I got confused as it disappeared at the same time I was trying to switch between OLS versions.

The transboundary information is useful for me in the AHIDA project where we're collecting information about Australian animals - the relevant breeds are sometimes Australia-specific, and sometimes transboundary, and with the subset information I can find both with a single API call

**Comment by sabrinatoro** [comment]
That makes sense. We will add them again. 
I don't know when the next VBO release will be, but if you need the information "asap", please let us know and we'll make sure to have one by early December.

**Comment by marius-mather** [comment]
If the transboundary information can be added back in ASAP, that would be great - we're getting close to a public release of AHIDA, and unless I can work out an alternative way to get the transboundary information (without making lots of API calls), it's hard to get the breed search working well.

**Comment by katiermullen** [comment]
The transboundary tags have been added back and will appear in the VBO release scheduled for the week of Dec. 4, 2023. Please feel free to re-open issue if further work is needed.
