### ISSUE TITLE
Create high level classification for VBO

### ISSUE THREAD

**Issue by katiermullen** [monarch-initiative/vertebrate-breed-ontology#129]
Users have suggested that it would be beneficial to have a hierarchy for breed that has a top level term "vertebrate breed" rather than the entirety of the NCBI Taxonomy.

Hierarchy would be:
Vertebrate breed
     -Cattle breed
     -Dog breed
     -etc.

Work is underway to create this high level classification scheme [here](https://docs.google.com/spreadsheets/d/14IB4VAyM0ZvLjksn_C2unZPomrOY_EeZAKpGNiOy4Xc/edit#gid=2071473913).

**Comment by sabrinatoro** [comment]
To do

- [ ] create new grouping classes
- [ ] add "vertebrate breed" as an "ontology root term"

**Comment by franknic** [comment]
Greetings, all
This is a great enhancement! As we have discussed, the NCBI taxonomy has been a serious impediment to showing users the power and utility of VBO.

**Comment by marius-mather** [comment]
This looks like a good change - it's nice to not show the whole taxonomy when displaying VBO. 

I just wanted to check and make sure that individual breed terms will continue to have their NCBI taxonomy species term as parent terms? I do some searches that filter on species by looking for children of the NCBI taxonomy term. My searches still seem to be working with the new release but just wanted to confirm this will be preserved in future.

**Comment by sabrinatoro** [comment]
Hi @marius-mather, yes, all the breeds still have their NCBI taxonomy (shown as parents, or "subclass of"), we are just not showing it in the ontology displayed in ols.

**Comment by katiermullen** [comment]
Closing this issue. Please see #141 for QC check info.
