### ISSUE TITLE
American miniature donkey

### ISSUE THREAD

**Issue by ImkeTammen** [monarch-initiative/vertebrate-breed-ontology#133]
Dear VBO team,

Can we please create a transboundary entry for 'Miniature donkey', with a synonym 'American miniature'.
PMID:25887951 states that these donkeys are present in France but VBO currently has only an USA entry:
[Miniature, United States of America (Ass)](http://www.ebi.ac.uk/ols4/ontologies/vbo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FVBO_0001922)
VBO:0001922  
http://purl.obolibrary.org/obo/VBO_0001922

****

For new term requests, please provide the following information:

## Preferred term label

(e.g., Asplenia)

## Synonyms

(e.g., Absent spleen)

## Textual definition

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/ubo)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by katiermullen** [comment]
Sure thing! Happy to add this breed. Thank you for this suggestion.
