### ISSUE TITLE
Duplicate rows for VBO:0000991 Icelandic Horse (Horse) in spreadsheets

### ISSUE THREAD

**Issue by marius-mather** [monarch-initiative/vertebrate-breed-ontology#134]
One issue that came up while trying to synchronize with DADIS in #121 was a duplicate row for VBO:0000991 (Icelandic Horse/Icelandic Pony) in the `dadistransbound.tsv` spreadsheet. Is it possible to remove the duplicate row?

Having to work around the duplicated row makes matching to DADIS entries a fair bit more complicated as we need to do more work to make sure everything stays in the same order if we drop the extra row.

**Comment by sabrinatoro** [comment]
@marius-mather This duplicated line comes from our obsoletion/merging pipeline. Removing the duplicated row would lead to more manual moving of data, which has caused problems and introduced errors. 
I have sent an email to discuss solutions.

**Comment by marius-mather** [comment]
Duplicate entries are now explicitly marked in the spreadsheet, this can be closed.
