### ISSUE TITLE
Merging grouping terms

### ISSUE THREAD

**Issue by katiermullen** [monarch-initiative/vertebrate-breed-ontology#137]
The following terms will be merged with breed term:

- [x] VBO:0000038 'Alpaca (Alpaca)' 
- [x] VBO:0000715 'Emu (Emu)'
- [x] VBO:0000087 Cassowary (Cassowary)
- [x] VBO:0001100 Ñandú (Nandu)
- [x] VBO:0000041 American Bison (American Bison)
- [x] VBO:0000882 Guanaco (Guanaco)
- [x] VBO:0001721 Vicuña (Vicuña)
- [x] VBO:0001223 Cailles (Quail) ["cailles" is the French word for "quail")
- [x] VBO:0001199 Sus scrofa (Pig)
- [x] VBO:0001098 Llhama (Llama)
- [x] VBO:0000931 Cheval (Horse) [cheval is the French word for "horse"]
- [x] VBO:0000068 buffalo (Buffalo)

Example, Alpaca (Alpaca)' is merged with 'Alpaca breed' defined as "Vertebrate breed of the taxon Vicugna pacos."

This is based on feedback in issue #135 from @LeroyGregoire that: "from the DAD-IS logic, transboundary breeds and species are just categorical fields." In cases where the species is used to represent the breed, these terms represent the same concept as the "breed" grouping terms. Since they represent the same concept, they will be merged.

**Comment by sabrinatoro** [comment]
Note that other terms might also need to be merged. For example: 

-VBO:0001223 - Cailles (Quail) ["cailles" is the French word for "quail")
-VBO:0001199 - Sus scrofa (Pig)
- VBO:0001099- Muscovy (Muscovy duck)
- VBO:0001098	Llhama (Llama)
- VBO:0000931	Cheval (Horse) [cheval is the French word for "horse"]
- VBO:0000714	Wild duck (Duck (domestic))
- VBO:0000085	water buffalo (Buffalo)
- VBO:0000086	Wild Water Buffalo (Buffalo)
- VBO:0000068	buffalo (Buffalo)
-

**Comment by katiermullen** [comment]
Added terms recommended above by @sabrinatoro. Thank you! Terms that "need more thoughts" have not been merged.
