### ISSUE TITLE
Merge 

### ISSUE THREAD

**Issue by ImkeTammen** [monarch-initiative/vertebrate-breed-ontology#146]
Dear Katie:

Wondering is we should consider merging
http://purl.obolibrary.org/obo/VBO_0200629 Great Pyrenees (Dog)
http://purl.obolibrary.org/obo/VBO_0201113 Pyrenean Mountain Dog (Dog)

as they appear to be synonyms.

For new term requests, please provide the following information:

## Preferred term label

(e.g., Asplenia)

## Synonyms

(e.g., Absent spleen)

## Textual definition

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/ubo)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by katiermullen** [comment]
@ImkeTammen Thank you for your request. I agree that these terms should be merged. The merged terms will appear in the next VBO release. Thank you for bringing this to my attention.
