### ISSUE TITLE
Add pig breed: Göttingen minipig

### ISSUE THREAD

**Issue by ImkeTammen** [monarch-initiative/vertebrate-breed-ontology#152]
For new term requests, please provide the following information:

## Preferred term label

Göttingen minipig

## Synonyms

Goettingen minipig, Goettingen miniature pig

## Textual definition

breed of pigs

## Suggested parent term

Sus scrofa

## Attribution

Source: OMIA breed ID 1222
PMID: 1162186 (this seems to be the first report in Pubmed - the pigs are widely used in biomedical research)

**Comment by katiermullen** [comment]
@ImkeTammen thank you for suggesting this new term. I will add it to VBO and it will appear in the next release.
