### ISSUE TITLE
Merge VBO:0000746 and VBO:0000828

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/vertebrate-breed-ontology#18]
VBO:0000746 and VBO:0000828 are both transboundary bread called 'Sahelian (Goat)'
It looks like these 2 records represent the same breed, and therefore these should be merged into one single record. 

@franknic and @ImkeTammen could you please confirm that these 2 records are indeed the same? Thank you!

**Comment by franknic** [comment]
Hi Sabrina
828 is definitely ok. I can't find 746 in the ROBOT outputs file I downloaded on 14th March. But in the DADIS file that is the foundation of VBO there is a transboundary breed called "ChÃ¨vre [Chèvre] du Sahel (Sahelian en Anglais)" that is a parent of just one breed-country, namely "ChÃ¨vre [Chèvre] du Sahel-Niger". I have checked the DADIS online information, and this second transboundary name, i.e. "ChÃ¨vre [Chèvre] du Sahel (Sahelian en Anglais)", has now been deleted by DADIS, and should, therefore be deleted from VBO. This means that the breed-country entry "ChÃ¨vre [Chèvre] du Sahel-Niger" should not have a transboundary parent, and, instead, should have species = goat as its parent. I hope this helps.
