### ISSUE TITLE
Missing goat entry

### ISSUE THREAD

**Issue by ImkeTammen** [monarch-initiative/vertebrate-breed-ontology#183]
This goat could be added - may not have breed organisation but considered a rare goat breed 

For new term requests, please provide the following information:

## Preferred term label
Vierhornziege 

## Synonyms
four-horned goat; fourhorn goat

## Suggested parent term
Goat

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/ubo)

## Attribution
https://de.wikipedia.org/wiki/Vierhornziege
If you would like a nanoattribution, please indicate your ORCID id

https://orcid.org/0000-0002-5520-6597

**Comment by katiermullen** [comment]
Thank you @ImkeTammen! We will add this rare breed of goat.

**Comment by katiermullen** [comment]
This breed has been added to VBO using the English language name "four-horned goat" with synonyms "Vierhornziege" and "fourhorn goat".
