### ISSUE TITLE
Add new NCBI Taxon for Cellosaurus request

### ISSUE THREAD

**Issue by katiermullen** [monarch-initiative/vertebrate-breed-ontology#187]
I would like to add the following new NCBITaxon to VBO:

NCBITaxon:59729, Taeniopygia guttata (Zebra finch)
NCBITaxon:10036, Mesocricetus auratus (Golden hamster)
NCBITaxon:186623, Actinopteri (ray-finned fish)
NCBITaxon:8022, Oncorhynchus mykiss (Rainbow trout)
NCBITaxon:7955, Danio rerio (Zebrafish)
NCBITaxon:7962, Cyprinus carpio (Common carp)
NCBITaxon:7957, Carassius auratus (Goldfish)
NCBITaxon:8090, Oryzias latipes (Japanese rice fish)
NCBITaxon:8353, Xenopus (Clawed frog)
NCBITaxon:8364, Xenopus tropicalis (Western clawed frog)

Confirmed these taxon are in https://obofoundry.org/ontology/ncbitaxon.html

**Comment by katiermullen** [comment]
@sabrinatoro May I add these new NCBITaxa and high level classification terms (e.g. 'Goldfish breed') for each of these new species to VBO?

**Comment by katiermullen** [comment]
<img width="909" alt="Screen Shot 2024-08-06 at 4 20 43 PM" src="https://github.com/user-attachments/assets/d924f4c5-2fc8-41e0-abe3-0421e65b2e7a">

**Comment by sabrinatoro** [comment]
@katiermullen 
I agree with defining fish breeds as breeds of Actinopteri. 
however I would still call the term "fish breed"
