### ISSUE TITLE
New entry for VBO 'Rangeland Goats'

### ISSUE THREAD

**Issue by ImkeTammen** [monarch-initiative/vertebrate-breed-ontology#188]
For new term requests, please provide the following information:

Dear Katie,

I couldn't find Rangeland goats in VBO - sorry if it is there and I missed it:

## Preferred term label
Rangeland (goats)

## Suggested parent term

Goat / capra hircus

## Source
https://www.goatindustrycouncil.com.au/goats-in-australia/rangeland-goats/ 👍 The rangeland goat is a composite breed of goat which has become naturalised throughout Australia’s rangelands and in other areas which offer natural protection against predators. These goats have effectively adjusted to the environment to the extent that they no longer bear any strong resemblance to the original breeds of domesticated goats introduced with European settlement.

If you would like a nanoattribution, please indicate your ORCID id

**Comment by katiermullen** [comment]
Will add. Thank you.

**Comment by katiermullen** [comment]
This goat breed has been added and will appear in the next update of VBO. Thank you @ImkeTammen!
