### ISSUE TITLE
Add synonym to http://purl.obolibrary.org/obo/VBO_0009377

### ISSUE THREAD

**Issue by ImkeTammen** [monarch-initiative/vertebrate-breed-ontology#189]
Dear Katie,

please add 'Australian Brown' as synonym to Australian All Brown, Australia (Goat) - VBO:0009377

Source: https://dairygoats.org.au/dairy-goat-breeds/australian-brown/

Regards,

Imke

**Comment by katiermullen** [comment]
Will add this synonym. Thank you.

**Comment by katiermullen** [comment]
This synonym has been added and will appear in the next update of VBO. Thank you @ImkeTammen!
