### ISSUE TITLE
Update names with special character - part2

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/vertebrate-breed-ontology#19]
- [ ]  make a list of all the VBO labels containing special characters (SPARQL query is same as in #9)
- [ ]  Frank/Imke will review the list and add the correct spelling (which will include accents,...)
- [ ]  Update VBO labels accordingly

note: part2 of revision of special character is necessary because some terms were missing in VBO and therefore were missed the first time.

**Comment by franknic** [comment]
Your closing of those other tasks has stimulated me to respond on this one, apologising for being so slow to get back to it. It's still high on my todo list, and I will get to it as soon as possible.

**Comment by franknic** [comment]
I've now worked through each of those two sets of names, and have pasted corrected words into the googles doc. Some of the words didn't change. There are bound to be some mistakes in what I have done, but we can proceed with the present revised versions, realising that there will almost certainly be some that will need correction in the future. Fortunately, as I have mentioned, the new DADIS download tools retain the original symbols, which is a great bonus.
