### ISSUE TITLE
Additional cat breeds

### ISSUE THREAD

**Issue by ImkeTammen** [monarch-initiative/vertebrate-breed-ontology#195]
Dear Katie,

the following reference
Jaito W, Singchat W, Patta C, Thatukan C, Kumnan N, Chalermwong P, Budi T, Panthum T, Wongloet W, Wattanadilokchatkun P, Thong T, Muangmai N, Han K, Duengkae P, Phatcharakullawarawat R, Srikulnath K. Shared alleles and genetic structures in different Thai domestic cat breeds: the possible influence of common racial origins. Genomics Inform. 2024 Jul 31;22(1):12. doi: 10.1186/s44342-024-00013-4. PMID: 39085978; PMCID: PMC11292921.

lists cat breeds that I could not find having a quick look at VBO
- Wichien Maat (WCM) and  Konja (KJ) 
- Khao-Manee may need to be added as synonym for Khao Manee (KM)

Regards,

Imke

**Comment by katiermullen** [comment]
@ImkeTammen 

Wichien Maat is a synonym for Thai according to https://en.wikipedia.org/wiki/Thai_cat

Konja is a synonym for Korn Ja according to https://en.wikipedia.org/wiki/Siamese_cat#History

These synonyms have been added.

Khao-Manee has been added as synonym for Khao Manee (KM)
