### ISSUE TITLE
Term request - pigeon

### ISSUE THREAD

**Issue by ImkeTammen** [monarch-initiative/vertebrate-breed-ontology#198]
Dear Katie,

please add the following pigeon breeds: 

Taihu Dianzi
Tarim

Parent: Columba livia

Source: PMID:38612286 (https://pubmed.ncbi.nlm.nih.gov/38612286)

**Comment by katiermullen** [comment]
These pigeon breeds have been added and will appear in the next update of VBO. Thank you @ImkeTammen!
