### ISSUE TITLE
Term request - chicken

### ISSUE THREAD

**Issue by ImkeTammen** [monarch-initiative/vertebrate-breed-ontology#199]
Dear Katie, 

Can we please add the following breed to VBO:

Bamaxiaogu (chicken)
parent: Gallus gallus
Source: Huang L, Guo Q, Sun J, Wang Z, Jiang Y, Chang G, Bai H. New findings on the genetic basis of feathered legs in chickens:association of CUBN gene mutations with feathered leg phenotype. J Anim Sci. 2024 Aug 27:skae252. doi: 10.1093/jas/skae252. Epub ahead of print. PMID: 39187978.

Thank you

**Comment by katiermullen** [comment]
This breed has been added and will appear in the next update of VBO. Thank you @ImkeTammen!
