### ISSUE TITLE
add annotation : country 

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/vertebrate-breed-ontology#20]
Add "country" as an annotation to VBO terms. 
- link to country in Wikidata
- create a new annotation property : "has country" or "bred in country" or... (TBD)

**Comment by sabrinatoro** [comment]
@franknic and @ImkeTammen 
We need a relation between the breed (VBO term) and the country. My understanding is that "country of origin" is not correct since "country" reported in DAD-IS does not represent the country of origin, but rather the country where the breed is found. Is this correct? 
Do you have any suggestions regarding what to call this relation in order to clearly express its meaning? Maybe something like: "bred in country", "has home country", ...

Please share your thoughts! Thank you in advance.

**Comment by franknic** [comment]
Yes, Sabrina, country is where the breed exists. We have encountered exactly the same wording challenge in OMIA where we often have a particular phene existing in more than one species, and we need a separate entry for the occurrence of that phene in each species in which it has been reported. Our solution has been to talk in terms of an entity called a phene-species, and this has worked fine. In the VBO context, we could then talk in terms of an entity called a breed-country, which refers to a particular breed that exists in a particular country. Does this help?

**Comment by sabrinatoro** [comment]
Thank you @franknic 
I am asking something a little different.
The VBO entity is definitely reflecting a "breed-country", and this will not change. 
I was planning on adding "country" as metadata to the breed-country. To do so, I would add the country as metadata (in addition to adding it to the label, not instead). 
For example, a term would look as follow: 
-   term label: Bali Cattle, Malaysia; Cattle
-   term ID: VBO:0002332
-   has_exact_synomym: Banteng
-   **exists_in_country: wikidata:Q833** _(= wikidata entry for Malaysia)_
-   SubClass_Of: 'Bali; Cattle' _(=parent term is this transboundary)_

My specific questions are therefore: 
- do you think we should **not** have "country" as metadata in addition to the "breed-country"? 
- if it is ok to have "country" as metadata, is the relation "exists_in_country" correct? or should we have another one? 

If this is still confusing, we can set up a in-zoom-person meeting soon. 
thanks!

**Comment by franknic** [comment]
Thanks, Sabrina, for pointing me to the VBO files. I promise not to touch any entry :)
Looking at your case example, the VBO table includes three other exact synonyms: Balinese|Lembu Bali|Bos banteng Are these included?
Having country as metadata is a good idea, and I can't see any disadvantage. 
And "exists_in_country" should work perfectly.
My only suggestion is in relation to the country codes. The Wikidata codes are fine, but it would add value if we also include the UN ISO standard codes. These are the ones used by, for example, Google analytics, and (I suspect) many other resources to which we would like to be linked. They are also the ones that are used by DADIS: the UN ISO standard three-letter country codes are included in the DADIS input file, and the numeric codes are available from https://www.iso.org/iso-3166-country-codes.html

**Comment by sabrinatoro** [comment]
done
