### ISSUE TITLE
add annotation : transboundary 

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/vertebrate-breed-ontology#21]
breeds that have a transboundary parent should get an annotation referring to the transboundary breed. 
to do: 
- create a new annotation property : has_transboundary_parent
- update VBO

**Comment by sabrinatoro** [comment]
@franknic @ImkeTammen

**Comment by franknic** [comment]
That sounds like a good strategy! There is just one point to be clarified. As shown in Imke's diagram from December last year (attached), the word "breeds" in your message above should actually be "breed-countries". In other words, there are breed-countries that have a transboundary parent, which, in turn, has a species parent; there are three levels in this hierarchy. There are also breed-countries that have just a species parent, i.e. they do not have a transboundary parent; there are just two levels in this hierarchy. We can neglect the bottom row in Imke's diagram for the time being - we haven't yet introduced any varieties.
I hope this helps.

![211202 Imke proposed breed data structure](https://user-images.githubusercontent.com/79228708/162091971-46626c3a-0fce-4555-ae30-d5c29003fbc6.png)

**Comment by sabrinatoro** [comment]
Thank you @franknic 
I am asking something a little different.
The VBO classification definitely reflects the classification that you mentioned, and will not be changed.
I was planning on adding "transboundary" as metadata to the breed-country. Adding this metadata would be a way to somehow tag the VBO terms that are transboundary (currently, transboundary are only findable based on their place in the ontology).   
The VBO classification would stay the same, and a term would look as follow: 
-   term label: Bali Cattle, Malaysia; Cattle
-   term ID: VBO:0002332
-   has_exact_synomym: Banteng
-   **has_transboundary_parent:  'Bali; Cattle' (VBO:0000125)** 
-   SubClass_Of: 'Bali; Cattle' **_(=parent term is this transboundary, this is the ontological way of saying what the parent is)_**

Note: I chatted with Nico, and it looks like adding this "has transboundary parent" metadata on the child, ie breed-country, is the best way forward. I will follow-up with him about why we should go this way instead of adding a tag on the transboundary entity (he probably said and I forgot). 

Does it make more sense?

**Comment by franknic** [comment]
Thanks, Sabrina
I think that is all fine, but I should check it in the actual ontology. I've searched for VBO:0002332 in the Robot Excel file I downloaded on 14th March, but can't find it there. And I can't find any Robot file in either the public or log-in section of the VBO GitHub site. Can you please direct me to where I can view the latest version of VBO?

**Comment by franknic** [comment]
Hi Sabrina
Having now looked at the VBO master spreadsheets, everything you have proposed in relation to transboundary names looks fine to me.
In relation to transboundary names, Imke and I received an email today from DADIS, saying that they have revised their transboundary names, removing those like the incorrect one we dealt with earlier (where a transboundary name had only one offspring breed-country). Over the weekend, I hope to be able to download a new dump of all the DADIS breed data, with the errant transboundary names presumably deleted. I will let you know as soon as I have had a look at the new dump, and we can ponder how best to deal with the changes.

**Comment by sabrinatoro** [comment]
done
