### ISSUE TITLE
post VBO to the monarch OLS instance

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/vertebrate-breed-ontology#29]
We should get it posted to the monarch OLS instance so that folks can more easily look at it.

Here is the background for this issue:
(...) recall from below that in his inital feedback, Zhiliang said:
“the VBO at the current status (as available from Github) are not ready. For example, there are many "nodes" but missing too many "edges" (connections); with many terms referred as `is_a` NCBITaxon number which is currently out of the picture. The current data can hardly claim to be an "ontology".”

Realising (as mentioned in my feedback) that he may have been looking at an old version preceding Sabrina’s latest GitHub update, I wrote again to Zhiliang, who still sees some problems:
“I downloaded with the link from your email 2 days ago. It cannot be loaded to an ontology viewer like AmiGO, or my in-house tool, and even cannot be opened by a desktop OBO Edit.  I manually checked through the list, and found 8700+ terms are missing parents.  It appears to be created with a script copying a breed list and forced to match ncbi tax terms while the taxonomy is not incorporated.”

Unfortunately, neither Imke nor I has yet learned enough about ontology files to be able to check Zhiliang’s feedback. Would you please check his comments against the current VBO files?

**Comment by sabrinatoro** [comment]
@matentzn, I don't know whether you would be able to do this, or I should ask someone else (I don't know the process). 
I am assigning this issue to you, but feel free to reassign it.  
I will add this to discuss at our next 1:1. Thanks!

**Comment by franknic** [comment]
Greetings, Sabrina and Nico
I hope it was ok for me to add Nicole, Imke and Katie to this issue.
My comments here follow on from Zhiliang's feedback with which you started this issue, Sabrina. 
Being very keen to show our local colleagues what has been achieved, and noting that the ICBO talk mentions VBO being on OBO Foundry, Imke and I looked there today. When we clicked on the download symbol (Download Vertebrate Breed Ontology in OWL format), the resultant file contains the words REDUCED_REDUNDANCY repeatedly, but no-where could we find any of the words that actually occur in VBO. And I couldn't see how to open it with Protege. When we did the same download for HPO, we got a file that looks like what we would expect, namely an OWL file for human phenotypes. And I can open and view it in Protege. 
We fully appreciate that we may be doing something wrong! In any case, we would be very grateful for guidance on how to show VBO in OBO Foundry to our local colleagues.
Also, relating back to the title of this issue, it would be extremely helpful to our programmer Marius if the 220506 release of VBO could be posted to the Monarch OLS. We realise that this release is very incomplete, but posting it would enable Marius to become familiar with VBO's structure and to start building the software infrastructure in OMIA and AHIDA for using VBO. This task is now at the top of his-to-do list.
With much thanks for all the progress that has been made.
Frank

**Comment by matentzn** [comment]
Hello @franknic 

1. For the download button to work you have to deal with this ticket: https://github.com/monarch-initiative/vertebrate-breed-ontology/issues/46
2. For OLS and Ontobee to update you simply  make a quick request on their trackers ([OLS](https://github.com/EBISPOT/OLS/issues), [OntoBee](https://github.com/OntoZoo/ontobee/issues)). This has to be done after (1). Now that you are in OBO, no need for Monarch OLS - you will go straight to the real OLS!

**Comment by franknic** [comment]
Thank you very much, Nico
Unfortunately, I am not sufficiently cognate to do this. But Imke and I will seek guidance from Marius, who I am sure will resolve all challenges.
Just one question: why are those steps necessary for accessing VBO but not for accessing HPO from the same resource? The very clear implication of the OBO Foundry download button is that it will provide a functional OWL file.

**Comment by matentzn** [comment]
@franknic the above steps are just configuration steps you as ontology owners have to do once. HPO and every other ontology had to go through the same. It is part of the registration process!

**Comment by franknic** [comment]
Thank you, Nico. I now understand!! Given that reality, and given that you are a key person in the VBO team, and given that Sabrina is pre-occupied with preparing for the forthcoming ICBO conference, would it be possible for you to do that part of the registration process?

**Comment by matentzn** [comment]
I did 1. You can now correctly download the file. You can now deal with 2) Just go here:

- https://github.com/EBISPOT/OLS/issues
- https://github.com/OntoZoo/ontobee/issues

And say: `VBO has recently been admitted to OBO Foundry (https://obofoundry.org/ontology/vbo.html). We kindly ask that you add it to OLS.` Or something similar.

**Comment by franknic** [comment]
Thank you very much, Nico! That is much appreciated. 
Sabrina or Nicole or Katie: it would be far more appropriate for one of you to do the final step. Is this possible?

**Comment by sabrinatoro** [comment]
Thank you so very much @matentzn !!! 
I'll create the issues in the trackers you shared in your last email.

**Comment by sabrinatoro** [comment]
https://github.com/EBISPOT/OLS/issues/636

https://github.com/OntoZoo/ontobee/issues/183

**Comment by franknic** [comment]
Thank you very much, Nico. I have now downloaded the OWL file and can view it in Protege.,
And thank you Sabrina for submitting those requests. I look forward to being able to direct Marius to OLS

**Comment by franknic** [comment]
Hi Sabrina
It is great that we can now download an OWL file from the Foundry. 
I'll start a new issue to enable us to report our experiences with the OWL file. And I'll ask Zhiliang and Cari to have a look.

**Comment by franknic** [comment]
Hi all,
Marius Mather has just informed Imke and me that VBO is now up on https://www.ebi.ac.uk/ols/ontologies/vbo. This is great news! Thank you, Nico, for showing us how to get to this stage, and Thank you, Sabrina, for making the requests.
Marius is now very busy writing code to enable OMIA and AHIDA to utilise VBO.

**Comment by franknic** [comment]
Hi Nico
I've had a look at VBO in the EBI OLS, and it looks good.
A question: in the documentation at https://www.ebi.ac.uk/ols/docs/website, there is mention of an advanced search tool, namely "By using the advanced search the user can further restrict the results to one or multiple ontologies or to a specific 'type'. Types can be class, property or individual. Using the advanced search you can restrict searches to one or more ontology". But I can't find any advanced search tool, and neither can I find anywhere to ask for help. Can you help?

**Comment by matentzn** [comment]
Hey @franknic 

If you go here:

https://www.ebi.ac.uk/ols/search?q=cat

You can click on "class" or "individual", select the ontology you want to search. Is that what you are looking for?

**Comment by franknic** [comment]
Thanks, Nico
Yes, that does enable me to choose between class or individual. But when I do that within VBO, it doesn't seem to be helpful. For example, if I search for Charolais within VBO (https://www.ebi.ac.uk/ols/search?q=charolais&ontology=vbo), I get 87 results which are all listed as class. Actually the first two results are at the transboundary level of the hierarchy and the other 85 are at the breed_country level of the hierarchy. I was hoping that the first two would be distinguishable from the other 85. 
However, I'm happy to leave it as is for the time being. I'll do some more investigating. Who knows what I will discover! 
Thank you very much.

**Comment by matentzn** [comment]
Ah no, you wont be able to distinguish transboundary from breed by country in a Generic Browser like OLS. For that, we will have to build custom VBO browsers.. Or use an entirely different approach to classification, where transboundary and other breed classes are in different hierarchies.

**Comment by franknic** [comment]
Thank you Nico. I'm learning every day! I'm happy to do what I can in the OLS.

**Comment by sabrinatoro** [comment]
This issue is done.
