### ISSUE TITLE
Add Cat Breeds

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/vertebrate-breed-ontology#34]
- [x] find sources for cat breeds
- [x] make breed list (include reconciling data from sources)
- [x] create ROBOT template
- [x] update VBO 
- [x] update documentation

Working documents: 
(to be added here)

**Comment by sabrinatoro** [comment]
Spreadsheet is here: https://docs.google.com/spreadsheets/d/19ltiiA66eKjQdNeWaLpaAxE9XoQRJiwXWOcLmugwzXo/edit#gid=0

**Comment by franknic** [comment]
This is excellent!! You have done a great job, especially with documenting the sources of each item of information, such as breed abbreviations. This looks to be the most comprehensive list every compiled! Feedback from people such as Leslie will identify any remaining issues. I spotted one typo in row 226: Simberian

**Comment by sabrinatoro** [comment]
@katiermullen I think we can close this issue. There are more things to do for the cat breeds, but I think these can have their own issue. 
If you agree, could you please close this issue? Thank you!

**Comment by katiermullen** [comment]
Closing this issue.
