### ISSUE TITLE
Livestock: add tags for "local breed", "national breed population"

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/vertebrate-breed-ontology#40]
DAD-IS distinguishes "local breed", "transboundary breed", and "national breed population". 
We currently have "'in subset' transboundary" annotations in the ontology. In order to clarify these different "types" of breeds as reported in DAD-IS, we should: 
1) create new subsets for "local breed", and "national breed population"
2) clearly define these concepts in the subset property type (ie add definitions and DAD-IS provenance)
3) add these subsets for all the breeds coming from DAD-IS

**Comment by franknic** [comment]
Hi Sabrina
Now that we have the DADIS definitions, I think the picture is a little clearer. When DADIS talks of "more than 15,000 national breed populations", it is referring to the total number of rows in the DADIS Excel file. This comprises an entry (row) for each local breed and an entry (row) for each transboundary breed in each country in which it occurs. Consequently, my understanding is that we don't have to worry about incorporating "national breed population" into VBO; it is simply a term used by DADIS to describe the entity that occupies a row in the spreadsheet. The total number of national breed populations is the total number of breeds (across all species) that occur in each country, summed over all countries.

**Comment by franknic** [comment]
I have come up with a definition that may be helpful. A national breed population is a breed in a particular species that has been reported in a particular country. As mentioned in the previous post, a national breed population is one row in the original DADIS spreadsheet, i.e. one row in the lowest level of the current VBO hierarchy. Some national breed populations have parent = transboundary breed; some have parent = species.

**Comment by sabrinatoro** [comment]
Thank you @franknic. 
Subsets were added for transboundary breed, national breed populations, and local breeds. In addition, I added: 
- definition from DAD-IS
- reference to DAD-IS
