### ISSUE TITLE
To start using the OBO Purls, add PURL config

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/vertebrate-breed-ontology#46]
To start using the OBO Purls, add PURL config. Here is an example you can use as a blueprint:

https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/pato.yml

Add a new file, `vbo.yml` into the `config` directory, make a pull request and tag me in a comment.

**Comment by sabrinatoro** [comment]
This issue has been resolved with 
https://github.com/OBOFoundry/purl.obolibrary.org/issues/869
https://github.com/OBOFoundry/purl.obolibrary.org/pull/870
