### ISSUE TITLE
update VBO name to using OMIA breed name

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/vertebrate-breed-ontology#5]
Document: OMIA breeds mapped to DADIS breeds
https://docs.google.com/spreadsheets/d/1__2tRGC-CQPoDul1Aa0WXy_W6t6HNWJl_VsEGvrKqIc/edit#gid=683020650

OMIA breed name should be used for VBO term label

!!!! UPDATED!!!!
The OMIA name should be synonyms of the VBO terms. 
The OMIA ids should be x-ref of the VBO terms. Note that these ids will be removed from the ontology after the update to VBO is done in OMIA.

**Comment by sabrinatoro** [comment]
1) Some DADIS names have more than 1 OMIA breed_name. How do I know which name is the correct one? 

73 | Holstein Friesian | 9913 | cattle | Holstein Friesian
-- | -- | -- | -- | --
755 | Holstein-Friesian | 9913 | cattle | Holstein Friesian

221 | Piedmont | 9913 | cattle | Piedmont
-- | -- | -- | -- | --
48 | Piedmontese | 9913 | cattle | Piedmont
753 | Piemontese | 9913 | cattle | Piedmont

2) What are the OMIA breed_ids? (I couldn't find them in OMIA)
Should they be added as x-ref to VBO terms?

**Comment by sabrinatoro** [comment]
from Frank:
The OMIA breed_ids are solely internal; they have never been included in any information made public in OMIA.
After all the existing OMIA breed names have been replaced with the DADIS/VBO equivalent, we should never again need to access the OMIA breed list nor to use the links between the OMIA breed list and VBO.

**Comment by sabrinatoro** [comment]
Update: the OMIA names and OMIA id will be added as synonyms and x-ref (note that these x-refs will be removed later as they are internal ids to not be shared with the public).

**Comment by sabrinatoro** [comment]
@franknic @ImkeTammen 
Could you please review the record in the yellow line in [this document](https://docs.google.com/spreadsheets/d/1__2tRGC-CQPoDul1Aa0WXy_W6t6HNWJl_VsEGvrKqIc/edit?usp=sharing), OMIA Breed->breed-country (line 190), also copied below: 

OMIA breed_id | OMIA breed_name | NCBITaxon_species_id | Xlookup NCBITaxon species name | DADIS Breed | DADIS Country
-- | -- | -- | -- | -- | --
502 | Schwerfurt | 9823 | pig | Schwerfurter Fleischrasse | Germany

This breed is not currently in VBO. I can add it, but I would need to know what the parent term should be: is there a transboundary name for this breed? or would the species be the parent? 
Thanks!

**Comment by franknic** [comment]
Hi Sabrina. This is an error on my part. This entry should have been included in the list of entries to be added to VBO (which I will provide very soon. So, yes, please add it now if that is easy, or I can add it to the forthcoming list. Whichever is easiest for you. There is no corresponding transboundary name for this breed. So, "Schwerfurter Fleischrasse_Germany" is a new breed_country, with parent =  Sus scrofa.

**Comment by sabrinatoro** [comment]
@franknic 
No problem! I will add 'Schwerfurter Fleischrasse_Germany' as a new breed with the parent = Sus scrofa.

I have additional questions, this time on the OMIA Breed-> transboundary sheet in the same [document](https://docs.google.com/spreadsheets/d/1__2tRGC-CQPoDul1Aa0WXy_W6t6HNWJl_VsEGvrKqIc/edit?usp=sharing).
Could you please review the lines in dark orange (at the top of the list, lines 3-10). These transboundary names are either not in VBO yet, or might be but with a different name. I can add them to VBO without a problem, but I first want to confirm that these are new. 
Please add your answer to the document (column 1). 
Thank you!

**Comment by franknic** [comment]
Hi Sabrina
I started answering the latest queries, and then my laptop broke down! It's under warranty,  but wont be operational until next Tuesday at the earliest! Today I'll try to answer the remaining queries via my ipad.
Regards
Frank
________________________________

**Comment by franknic** [comment]
Hi Sabrina
I am very sorry for having still not answered those other questions. I've had to buy a new ipad to use while my laptop is out of action, and setting it up today has been a very frustrating business. I hope to be able to do them tomorrow.
Depressingly, my laptop will be out of action until 7th March at the earliest!!


________________________________

**Comment by sabrinatoro** [comment]
Note for future self: 
The omia information (xref and exact synonym) was added by creating a new component. 
The official sources are the following: 
OMIATRANSBOUND ="https://docs.google.com/spreadsheets/d/e/2PACX-1vRUoJ2t9244HHviSsC-Q6q59dxVBUMi85NUkWQFkIz87mUZ9wVqWyJ9foNJWl_Pkr3lFj57NJzpodBc/pub?gid=633566774&single=true&output=tsv"
OMIABREEDS ="https://docs.google.com/spreadsheets/d/e/2PACX-1vRUoJ2t9244HHviSsC-Q6q59dxVBUMi85NUkWQFkIz87mUZ9wVqWyJ9foNJWl_Pkr3lFj57NJzpodBc/pub?gid=1354068566&single=true&output=tsv"


As of 220903: 
8 lines in omiatransbound were not added as I am waiting on feedback from Frank. 
to do: add these missing lines to the ROBOT-omiatransbound document

**Comment by franknic** [comment]
Greetings, Sabrina
I'm pleased to report that my laptop is now functional again, and I will address all the remaining questions within the next 24 hours

**Comment by franknic** [comment]
Hi Sabrina
I'm very pleased to report that I've now answered all of the questions in lines 3-10.
Over the weekend, I'll work on the new entries to be added. Can you please remind me of how I should do this in the manner that would be most convenient for you? (I think you have told me this already, but, to make sure I do the right thing, it would be much appreciated if you can repeat the strategy.)

**Comment by sabrinatoro** [comment]
Thank you @franknic !
All the omia id and synonyms have been added to VBO. 
I will send you an email regarding submitting new entries.

**Comment by franknic** [comment]
Hi Sabrina
I've now added new transboundary names (rows 4-11) and breed-country names (rows 12-33). I will be very happy to make any changes that might be necessary. 
Each of these needs to be mapped to one or more OMIA breed names. What is the best way for me to do this?
