### ISSUE TITLE
Requests to add non-canine breeds to VBO

### ISSUE THREAD

**Issue by franknic** [monarch-initiative/vertebrate-breed-ontology#56]
**ST Update:** Terms requests are in this spreadsheet: https://docs.google.com/spreadsheets/d/12MYh8ktD2EPtoMIoMFlvdzPdSD5dnDu5/edit#gid=1150313493

For new term requests, please provide the following information:

## Preferred term label

(e.g., Asplenia)

## Synonyms

(e.g., Absent spleen)

## Textual definition

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/ubo)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by franknic** [comment]
Hi Sabrina
I've created this issue in the hope that this is a helpful means for adding new breeds to VBO. If there is a better way, then please make whatever changes are necessary. I've created a spreadsheet in the VBO shared drive entitled "Requests for non-canine breeds to be added to VBO", and have included just two breeds, as a trial run. Again, if there is a better way to do this, please make whatever changes are necessary.

**Comment by sabrinatoro** [comment]
@franknic 
Can you please confirm that there are only 2 terms requested based on the spreadsheet [here](https://docs.google.com/spreadsheets/d/12MYh8ktD2EPtoMIoMFlvdzPdSD5dnDu5/edit#gid=1150313493)?

**Comment by franknic** [comment]
Yes, there's just two, as a trial. As suggested, I did this through Github, where I opened a new issue #56, in which I explained that I had submitted just two requests as a trial, via the new spreadsheet in the VBO shared drive. I stressed that if there is a better way to submit requests, then please do whatever is needed to create a better strategy.
The more automated the strategy, the better for all of us. Our ultimate aim would be to have a strategy in place whereby if an OMIA/AHIDA curator encounters a breed not yet in VBO, while entering new information, a request to add a new breed could automatically be submitted (including the provenance for that breed).
Incorporating whatever changes in strategy that emerge from this trial, my aim now is to submit a long list of requests early in November, hopefully for inclusion in the November release. But if that inclusion is not feasible, that will be fine. I fully understand that there is a lot happening right now!
________________________________

**Comment by sabrinatoro** [comment]
@franknic 
I want to make sure that provenance is recorded correctly: is the location (Indonesia) from the PMID:3759678 ? (I don't have access to the publication so I couldn't check).

**Comment by sabrinatoro** [comment]
(we can review how to request new terms at our next meeting.)

**Comment by ImkeTammen** [comment]
Dear Sabrina,

the paper is freely available at PUBMEDhttps://pubmed.ncbi.nlm.nih.gov/3759678/

Three breeds of Javanese sheep are described briefly and data suggesting the segregation of a gene with large effect on ovulation rate and litter size are presented. The three breeds are Javanese Thin Tail (JTT), Javanese Fat Tail (JFT) and Semarang (SEM), the last possibly a substrain of JTT  - and the paper states that the sheep used in the study were from Indonesia

**Comment by sabrinatoro** [comment]
Thank you @ImkeTammen  
I do not have access to the full paper, only the abstract (it might be dependent on the institution). Based on the fact that the paper states that the sheep used in the study were from Indonesia, I think I can add the paper as a source for the country information.

Note: the paper mentions 3 breeds but the request is only for 2. I am assuming that the 3rd breed will be requested in the next request. (I just want to make sure so we don't miss any.

**Comment by ImkeTammen** [comment]
One of them - the JTT is already in VBO as a synonym of an existing DADIS/FAO breed

**Comment by franknic** [comment]
Greetings, all
I’ve just got back to my laptop.
The email thread has covered all relevant issues.
I am happy to confirm that the PMID is an authoritative refereed paper and definitely mentions all three breeds as being Indonesian. And yes, JTT is already in VBO, so it’s only the other two that need to be added.
Regards
Frank

Read about the Pioneers of Mendelian inheritance in animals<https://omia.org/key_articles/pmia/>
For an up-to-date list of animal traits/disorders characterised at the DNA level, and for tables of likely causal variants, visit Online Mendelian Inheritance in Animals (OMIA)<https://omia.org/>
OMIA has been on the internet for 27 years, since 26 May 1995. Share its 25th birthday celebrations<https://www.sydney.edu.au/science/news-and-events/2020/05/25/online-mendelian-inheritance-animals.html>
To help retain OMIA as a freely-available resource, please make a donation<https://omia.org/donate/>
To join the OMIA Support Group, register at https://www.animalgenome.org/community/omia-support/
