### ISSUE TITLE
Request new mappings of OMIA breed ids to existing VBO ids

### ISSUE THREAD

**Issue by franknic** [monarch-initiative/vertebrate-breed-ontology#63]
Hi Sabrina
From an OMIA download provided by Marius, I've created a list of OMIA breed ids that can be mapped to existing VBO ids. What is the best way to submit this list? Would it be OK to do it via the template for requesting new VBO terms, by simply populating the OMIA breed id column and a new column for the corresponding VBO id?
In some cases, I would be requesting one or more new synonyms, which I could include in the synonym column.

**Comment by sabrinatoro** [comment]
Hi Frank, 
yes, a spread sheet with the vbo id and the corresponding omia id would be best. 
You can add a synonym column if you have synonyms. You can put all the synonyms in the same cells, separated by pipe ( | ).
Therefore the spreadsheet would have the following columns (in whatever order): 
VBO ID, OMIA ID, synonym(s). 
Thank you!

**Comment by franknic** [comment]
Thank you, Sabrina
I've uploaded a file entitled "Template for mapping OMIA breeds to VBO terms_FN221111" to 
[https://docs.google.com/spreadsheets/d/1b3J-UTnCRSJdQ5ZokYpML1Gh3HW_fhxw/edit#gid=27533064](url)
Please let me know if anything else is required.

**Comment by sabrinatoro** [comment]
@katiermullen has updated the "component" spreadsheet.
@sabrinatoro has reviewed.
These changes will be in the ontology once we "update components".
