### ISSUE TITLE
Request for new terms to be added to VBO FN221110

### ISSUE THREAD

**Issue by franknic** [monarch-initiative/vertebrate-breed-ontology#64]
Hi Sabrina
It turned out that there are only a small number of OMIA breeds that are not in VBO. I've just prepared a template doc (Template for new VBO terms_FN221110) for four new terms, which is in the folder [https://drive.google.com/drive/folders/1NS4MQ6T0XSjlbOkYfEfQChpQq-PeoXG3](url). I think its actual link is as given below, but I'm not sure about that:
[https://docs.google.com/spreadsheets/d/1hJQYiM8NScT16f2T3xPAUAiIUm5B4So7/edit?usp=share_link&ouid=106020217318760834214&rtpof=true&sd=true](url)
I would be very happy to respond to any requests for more information, or for the information to be submitted differently.

**Comment by sabrinatoro** [comment]
@katiermullen has updated the spreadsheet, @sabrinatoro has reviewed. 
We need to update the components to see this change in the ontology.
