### ISSUE TITLE
EBI OLS slow to pick up VBO new release

### ISSUE THREAD

**Issue by franknic** [monarch-initiative/vertebrate-breed-ontology#67]
Greetings, all
I've been checking EBS OLS [https://www.ebi.ac.uk/ols/ontologies/vbo](url) regularly, and it has not yet picked up the October VBO release. In contrast, ontobee [https://ontobee.org/ontology/vbo](url) picked it up within a few days of release.

**Comment by matentzn** [comment]
For this, make an issue on OLS https://github.com/EBISPOT/OLS/issues

They are in a phase of big transformative change and sometimes need to be poked to pick changes up! Many people do it all the time :)

**Comment by franknic** [comment]
Done! It’s issue #651
Thanks, Nico

Read about the Pioneers of Mendelian inheritance in animals<https://omia.org/key_articles/pmia/>
For an up-to-date list of animal traits/disorders characterised at the DNA level, and for tables of likely causal variants, visit Online Mendelian Inheritance in Animals (OMIA)<https://omia.org/>
OMIA has been on the internet for 27 years, since 26 May 1995. Share its 25th birthday celebrations<https://www.sydney.edu.au/science/news-and-events/2020/05/25/online-mendelian-inheritance-animals.html>
To help retain OMIA as a freely-available resource, please make a donation<https://omia.org/donate/>
To join the OMIA Support Group, register at https://www.animalgenome.org/community/omia-support/

**Comment by sabrinatoro** [comment]
Thank you for answering @matentzn.
As Nico mentioned, this is an issue for OLS, and not for VBO. 
Closing this issue.
