### ISSUE TITLE
VBO:0000012 has no parent

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/vertebrate-breed-ontology#74]
https://www.ebi.ac.uk/ols/ontologies/vbo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVBO_0000012&lang=en&viewMode=All&siblings=false

VBO:0000012 should have a parent. It currently does not.

**Comment by LeroyGregoire** [comment]
Can't really say but this would correspond to crosses between dromedary and bactrian camels...
