### ISSUE TITLE
Change Transboundary name ‘Iceland Pony’ to 'Icelandic Horse'

### ISSUE THREAD

**Issue by ImkeTammen** [monarch-initiative/vertebrate-breed-ontology#75]
Please change the transboundary breed : Iceland Pony (Horse) [http://purl.obolibrary.org/obo/VBO_0000990 - OMIA:826](https://protect-au.mimecast.com/s/3ZpCCXLW2mUnAzl1pikCoPi?domain=purl.obolibrary.org) to: ‘Icelandic Horse (Horse)’ and keep ‘Iceland Pony’ as a synonym. I had requested the name change with the DADIS/FAO team and this has now occurred in DADIS. 

DADIS continues to list the Icelandic Horse population in Iceland as a ‘country breed’ which is in DADIS not connected to any transboundary breed. Gregoire commented: “Regarding the fact that Iceland does not link to Islenski Hesturinn to the transboundary Icelandic horse breed, there seems to be a reason to that, in relation to the fact that the Iceland national breed population is actually closed to any foreign population from Icelandic horse, and thus considered as an independent local breed.” This is true – Iceland does not allow the import of horses and the Icelandic horse in the only horse breed in Iceland. However, the Icelandic horse populations in other countries have been generated from horses exported from Iceland (and this is an ongoing practice with regular export of horses from Iceland) and at least in some countries are linked via a studbook to the Icelandic populations. Thus the breeds in other countries are directly linked to the Icelandic horse population in Iceland.

In VBO the Icelandic Horse in Iceland is listed as ‘Islenski Hesturinn, Iceland (Horse) [http://purl.obolibrary.org/obo/VBO_0010715](https://protect-au.mimecast.com/s/6NP8CVARKgClBRV7OuzFoBy?domain=purl.obolibrary.org)’ and linked to a transboundary (Icelandic Horse (Horse)  [http://purl.obolibrary.org/obo/VBO_0000991](https://protect-au.mimecast.com/s/dDcnCROND2urYzwJ7U9IRPC?domain=purl.obolibrary.org)’ that was created in the process of creating transboundary breed names for breeds without a transboundary breed in DADIS. The problem is that after the requested name change we now have two ‘Transboundary: Icelandic Horse (Horse)’ in VBO [http://purl.obolibrary.org/obo/VBO_0000991](https://protect-au.mimecast.com/s/dDcnCROND2urYzwJ7U9IRPC?domain=purl.obolibrary.org) and http://purl.obolibrary.org/obo/VBO_0000990?

I would probably merge them under http://purl.obolibrary.org/obo/VBO_0000990 as the international populations are all the result of historic or recent exports – so genetically they are one population – but this would be different to how this is handled by DADIS  ….

**Comment by sabrinatoro** [comment]
solved with February release
