### ISSUE TITLE
Update names with special character

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/vertebrate-breed-ontology#9]
- [x] make a list of all the VBO labels containing special characters (Sabrina, will use the SPARQL syntax given by Nico)
- [x] Frank/Imke will review the list and add the correct spelling (which will include accents,...)
- [x] Update VBO labels accordingly

Note: protege will accept the spelling containing accents,...

**Comment by sabrinatoro** [comment]
The query is in the src/sparql/reports folder

**Comment by sabrinatoro** [comment]
The list of term labels and synonyms with special characters is [here](https://docs.google.com/spreadsheets/d/1fvdK-GH9wdn5WKszpgyeU5GI3GlX94H7QQRty-lBswA/edit?usp=sharing)
There are 2 sheets: 
- one reporting term labels with 'weird' characters
- one reporting synonyms with 'weird' characters

@franknic @ImkeTammen : 
Please review these 2 lists (the label one is more important than the synonym one), and add the correct spelling in the spreadsheet (note that if it looks ok in the spreadsheet, it will look ok in protege). If no change should be done, please add a note.
Please let me know when you are done, I will update the labels in VBO. 

Note that this is not super urgent, therefore you can take your time to review these lists.
Thanks!

**Comment by franknic** [comment]
Hi Sabrina
Today I started working through the weird character file, following on from Imke's much-appreciated efforts. It's a very slow business, because just about every one has to be checked against the online version of DADIS. At my current rate, it could take me 40 hours to finish the list! I am, therefore, wondering if we can automate this process a bit. To this end, I am assembling a table equating the weird characters to the correct characters, and there does seem to be a one-to-one correspondence. My table so far is given below. Is is feasible to consider using a table like this to create the correct words? There would be a bit of a risk in going down this route, but the alternative (doing it manually) is quite daunting. I am happy to do the extra work required to create a complete table.

â€™ | ‘
Å¡ | š
Ã© | é
Å‚ | ł
Ã¥ | å
ÃŸ | ß
Ã§ | ç
Ã¶ | ö
Ä‡ | æ
Ã¼ | ü
Å» | Ż
Åº | ź
Å„ | ń
Ã± | ñ
Ã | à
Ä± | ı
Ã¤ | ä
Ã¨ | è
Å½ | Ž
Ã‘ | Ñ
Ãº | ú
Ã¡ | á
Åš | Ś

**Comment by ImkeTammen** [comment]
Dear Frank,

Yes once I had started I thought that copying the column and doing a find and replace would have been a more straightforward option …..

Imke

**Comment by franknic** [comment]
Thanks, Imke
Yes, that does seem to be the best strategy.
I’ll continue to work through the page I’m on, until I think I’ve got all the characters, and then I will have a go at some global finding and replacing in text copied into a local Excel file.

For an up-to-date list of animal traits/disorders characterised at the DNA level, and for tables of likely causal variants, visit Online Mendelian Inheritance in Animals (OMIA): https://omia.org<http://omia.angis.org.au/>
OMIA celebrated its 25th birthday on 26 May 2020: to share in the virtual celebration, click here<https://www.sydney.edu.au/science/news-and-events/2020/05/25/online-mendelian-inheritance-animals.html>.
To help retain OMIA as a freely-available resource, please make a donation at https://omia.org/donate/
To join the OMIA Support Group, register at https://www.animalgenome.org/community/omia-support/

**Comment by sabrinatoro** [comment]
@franknic and @ImkeTammen : thank you for doing this work. 
I agree, I think the best strategy at this point is to "find and replace" within the document. 
Also please remember that there is no urgency on this (the records in VBO are still there and available), and it will take whatever time is needed.

**Comment by franknic** [comment]
Greetings, all
I've had another session on the first page this afternoon, and the find and replace strategy worked very well in a trial run up to row 100. I'm now prepared to do the same for all the remaining rows next chance I get. And then I should be able to do the same for the other sheet.

**Comment by franknic** [comment]
I've just finished the first sheet, and should be able to do the second sheet in far less time, using the conversion table I have created. It is likely that there will be some mistakes, but we can correct those as we spot them. Thanks again to Imke for all your contributions.
One issue that has arisen in communication with DADIS: the transboundary name "Green-Legged partridge" should be deleted; for any breed-country that has this transboundary name as its parent, the new parent should be species = chicken. In other words, the breed-countries with this transboundary name are actually local breeds, occurring in only one country.

**Comment by franknic** [comment]
I should have added that, in the interest of time, I have not included language for most entries, as Imke has done. Given that I have prepared most of the entries via a find and replace strategy, entering language would have been an additional lengthy task. If there is any doubt about the language for a particular entry, I should be able to resolve it.

**Comment by franknic** [comment]
Back again, having finished both sheets! For the second sheet, I have populated the column headed "updated label (with correct spelling)". I've also created a new heading "updated ?exactsyn" which now contains the correct spelling for all entries in the original "?exactsyn" column. As with the other sheet, I have not given every language. In this case the only languages mentioned are those using different scripts, namely Bulgarian, Korean and Chinese.
So, these two sheets are now ready to go!
Thanks again to Imke for doing all the German entries.

**Comment by sabrinatoro** [comment]
Note to self: 
I updated the breed and transboundary labels with the correct (without weird characters) spelling. 
Note that some terms were missed in the report, probably because the report was done before we solved the issue of "missing ID" due to some format issues in some of the comments.

**Comment by franknic** [comment]
Thanks, Sabrina
Are there any parts of that third sheet that need my attention? 
In relation to dogs and cats, Imke and I have now received legal advice on the copyright issues, and it looks as if we may well be able to start compiling those entries next week.

**Comment by sabrinatoro** [comment]
Thank you @franknic !
At this point, nothing needs your attention: I need to figure out a few things first, including how to update the ontology with the current list of correctly spelled synonyms. 
I will tag you here and let you know when I have more work for you. 
Thank you for being so attentive and responsive!

**Comment by sabrinatoro** [comment]
The first round of revision is complete. I will close this issue and create a new one to review the labels that we missed.

**Comment by franknic** [comment]
Thank you, Sabrina. That's great progress!
