### ISSUE TITLE
Dorper sheep vs White Dorper

### ISSUE THREAD

**Issue by ImkeTammen** [monarch-initiative/vertebrate-breed-ontology#92]
Hi Sabrina,

Dorper sheep http://purl.obolibrary.org/obo/VBO_0001397 have currently White Dorper as an exact synonym. Dorper are black-headed sheep and I would argue that White Dorper are a separate transboundary breed that has been developed from crossing Dorper's with a different breed to create the White Dorper. So White Dorper are not an exact match to Dorper. See https://en.wikipedia.org/wiki/Dorper. In Australia they are considered two breeds that are looked after by the same breed association: https://www.australiandorper.com.au/

Can I please request  a new trans boundarybreed term 'White Dorper'

For new term requests, please provide the following information:

## Preferred term label

(e.g., Asplenia)

## Synonyms

(e.g., Absent spleen)

## Textual definition

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/ubo)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by sabrinatoro** [comment]
@ImkeTammen 
currently VBO:0001397 has 2 x-refs to OMIA: OMIA:977 and OMIA: 1251
Which one refers to "white dorper" and which one refers to "dorper"? 

thanks!

**Comment by sabrinatoro** [comment]
I am wondering whether "white dorper" is a specific type of "dorper". 

Based on https://smallfarms.cornell.edu/2011/01/dorper-sheep-truths-and-myths/
"Two varieties of Dorper Sheep were created: the black headed Dorper and an all white variety, the White Dorper sheep."

**Comment by sabrinatoro** [comment]
spreadsheets updated, the ontology will be updated once the components are updated.
