### ISSUE TITLE
American Miniatur Horse: VBO_0000896 

### ISSUE THREAD

**Issue by ImkeTammen** [monarch-initiative/vertebrate-breed-ontology#94]
Dear Katie and  Sabrina,
Please swap synonyms for American Miniatur Horse: VBO_0000896

Currently  displays as "American Miniatur Horse (Horse)" with the Synonyms:
American Miniatur Horse and American Miniature Horse

As 'Miniatur' is German may be bettter to use English spelling 'Miniature' for main term and German name as synonym? - requested by Elizabeth Esdaile <esesdaile@ucdavis.edu> who emailed OMIA.

Best regards,

Imke

**Comment by sabrinatoro** [comment]
Hi @ImkeTammen, 
I want to make sure I understand the request. Your request is:  
**update the term label** to "American Miniature Horse (Horse)" 
Is that correct?

**Comment by sabrinatoro** [comment]
spreadsheet updated. Ontology will be updated when we update components.
