### ISSUE TITLE
American Trotter/Standardbred (VBO_0000899) Synonyms

### ISSUE THREAD

**Issue by EEsdaile** [monarch-initiative/vertebrate-breed-ontology#95]
I propose that "American Trotter" be moved to a synonym and that "Standardbred" be used as the primary term for VBO_0000899. 

The term "Standardbred" is used internationally to refer to the breed, and it encapsulates both the trotting and pacing subpopulations. The term "Trotter" can refer to the breed as a whole or a subpopulation based. Some countries that refer to the breed as a "Trotter" only have horses from the trotting subpopulation and do not allow pacers. This is already reflected in the names of the sub-groups in VBO.

A partial list of organizations that refer to the breed as Standardbreds:
United States Trotting: http://fanguide.ustrotting.com/
Standardbred Canada: https://www.standardbredcanada.ca/content/new-racing-history-standardbred.html
Harness Racing New Zealand: https://www.hrnz.co.nz/industry-information/getting-started/about-standardbreds/
British Harness Racing Club: http://www.bhrc.org.uk/racing/the-sport/about-harness-racing/
Irish Harness Racing Association: https://www.irishharnessracing.com/elementor-history-of-the-sport

**Comment by sabrinatoro** [comment]
spreadsheet updated, will be visible in the ontology once components are updated
