### ISSUE TITLE
New Terms: Racking Horse and Spotted Saddle Horse

### ISSUE THREAD

**Issue by EEsdaile** [monarch-initiative/vertebrate-breed-ontology#99]
Hello, I propose that Racking Horse and Spotted Saddle Horse are added to VBO. Please find the required information below, and I am happy to provide additional information if needed.

## Preferred term label
Racking Horse (Horse)

### Synonyms
None known

### Textual definition
Racking horses are a gaited breed of horse that originated in America and are the state horse of Alabama. They are known for their singlefoot gait. https://www.rackinghorse.org/ https://encyclopediaofalabama.org/article/horses-in-alabama/

### Suggested parent term
Equus caballus (NCBITaxon:9796)

### Attribution
https://orcid.org/0000-0001-6238-9793

## Preferred term label
Spotted Saddle Horse

### Synonyms
None known

### Textual definition
The Spotted Saddle Horse is a naturally gaited horse breed characterized by spotted color patterns such as tobiano and overo.
https://nssha.com/
https://www.sshbea.org/
https://imh.org/exhibits/past/breeds-of-the-world/north-america/spotted-saddle-horse/

### Suggested parent term
Equus caballus (NCBITaxon:9796)

### Attribution
https://orcid.org/0000-0001-6238-9793

**Comment by sabrinatoro** [comment]
The new terms have been added to VBO, and will be available after the upcoming release.
Please see below the IDs corresponding to these terms:

VBO:0016883 - Racking Horse (Horse)
VBO:0016884 - Spotted Saddle Horse (Horse)
